-- SQL de referência para estrutura do plugin Mapa Político (manual)

CREATE TABLE wp_mapa_politico_locations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  city VARCHAR(120) NOT NULL,
  state VARCHAR(10) NOT NULL,
  postal_code VARCHAR(20) NULL,
  address VARCHAR(255) NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE wp_mapa_politico_politicians (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  location_id BIGINT UNSIGNED NOT NULL,
  full_name VARCHAR(180) NOT NULL,
  position VARCHAR(120) NOT NULL,
  party VARCHAR(100) NULL,
  age TINYINT UNSIGNED NULL,
  biography TEXT NULL,
  career_history TEXT NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  photo_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE wp_mapa_politico_politician_meta (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  politician_id BIGINT UNSIGNED NOT NULL,
  meta_key VARCHAR(120) NOT NULL,
  meta_label VARCHAR(190) NOT NULL,
  meta_type VARCHAR(30) NOT NULL,
  meta_value LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
